### ISSUE TITLE
Need the ability to enter negative values in the pressure field or probes

### ISSUE THREAD

**Issue by jgonz219** [landfill-eforms/landfill-android-app#1]
This was previously brought up 4/4 email "Previously I tried the probes and could not enter a negative value for the pressure (not the barometric), there was no negative sign on the keypad." [I thought it got fixed at one point]. Professor Sue Fixed this bug. Needs to be committed.

**Comment by jgonz219** [comment]
pressure h2o could be negative

**Comment by William-Andrews** [comment]
Just noticed that the Barometric pressure for probes was set to be able to enter negative.  It needs to be the Pressure H2O.
