### ISSUE TITLE
Have probes change color when pressure exceeds certain absolute values. (Somewhere I had asked for the probes to display the data in different colors based upon the readings (the methane and/or the pressure).) 

### ISSUE THREAD

**Issue by aadame95** [landfill-eforms/landfill-android-app#12]

**Comment by aadame95** [comment]
Was already implemented for methane but would like to confirm values and would like h2o values so they are applied as well

**Comment by SafaMahbub** [comment]
I was looking at the Functional Requirements and Design Document from the previous year I found the following color selections for the different forms:
Instantaneous (CH4/Methane): < 200 = black/200-499 = yellow/orange, 500+ = red.
Integrated (CH4/Methane): 1-9 = green or black, 10-24 = yellow/orange, 25+ = red.
Probe (CH4/Methane): 0.0 = green or black, 0.1-4.9 = yellow/orange, 5.0+ = red. 
Probe (H2O Pressure): -0.1 - 0.1 = green or black, 0.2-0.9 yellow/orange, 1.0+ = red.
If there are any modification to this we can ask at this Friday's meeting.

**Comment by SafaMahbub** [comment]
Seems like it was already implemented for Instantaneous and Integrated.
I am able to change the probe data.
For all of these, the default is not black/green, instead it is white to better pop out with our design scheme.
I can commit the changes once we get the okay that these parameters are up-to-date this Friday.
