### ISSUE TITLE
Entering a value such as 24.9999 (and submitting) for integrated will prevent it from being edited to another value successfully.

### ISSUE THREAD

**Issue by jgonz219** [landfill-eforms/landfill-android-app#7]
What does this mean “edited to what value”? To another form?

**Comment by jgonz219** [comment]
check with william

**Comment by aadame95** [comment]
there was logic behind it when it was first made which allows to be edited only when the value is increasing

**Comment by William-Andrews** [comment]
When I entered a value of 1.5 or 12 or 550 in the field for the Integrated reading (and moved on to a different field or saved), I could edit it (up or down).  Entering values with many decimal digits prevented any edits to the value.
