### ISSUE TITLE
I got a data validation error on entering a hotspot.  I moved it down from the initial Instantaneous value.  The error said that it must be above 500

### ISSUE THREAD

**Issue by jgonz219** [landfill-eforms/landfill-android-app#8]
This looks like it's been fixed already. the only validation error for a hotspot is " A warmspot entry must have CH4 levels between 200 and 500"

**Comment by jgonz219** [comment]
Confirm with William

**Comment by William-Andrews** [comment]
Warmspots are between 200 and 500, hotspots(IME's) are >500.  I don't recall exactly the error process, but I think that I went to change the prepopulated value and got the error.    Must be when I entered a value in the Inst. form, had the pop-up ask to edit the IME, said yes, then tried to change the CH4 value.  That is when the problem occurs.

Understanding the relationship between IME CH4 readings and those on the grids can be difficult to grasp.  I will try to come to the next meeting armed with a diagram that can help.
